#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# probe_marker_footer_tolerance -- prove a trailing attribution footer no longer silences an @agy marker, and that a buried marker still does not count.
"""Falsification suite for the four trailing-marker trigger tests.

THE INCIDENT
------------
2026-09-18, issue #38. A task comment ending in `ccp @agy-plan` was posted so
the planner would run. It never ran. Read back from the API, the stored body
ended with:

    ---
    _Generated by [Claude Code](https://claude.ai/code)_

The attribution footer is appended by the platform AFTER the body is
submitted -- measured on two independent routes (the GitHub MCP tool and a
raw urllib POST carrying a PAT), and a PATCH that deliberately placed the
footer mid-body had it moved back to the end. So the author cannot keep the
marker last, and `case "$LOWER" in *"@agy-plan")` matched nothing. The comment
looked right to every human who read it and triggered exactly nothing: a
trigger that cannot fire, which is the same family as a check that cannot
fail.

WHAT IS TESTED, AND THE HALF THAT MATTERS MORE
----------------------------------------------
The check-marker step is extracted from each of the four workflows and RUN as
a shell script against real bodies. Tolerating the footer is the easy half. The
half that keeps this honest is the negative side: a marker buried in the
middle of a comment, or absent entirely, must still NOT fire -- otherwise the
fix has turned a precise trigger into "mentions @agy-plan anywhere", and any
quoted example or discussion of the marker would dispatch the fleet.

ASCII only. Exit 0 pass, 1 fail.
"""

import io
import json
import os
import re
import subprocess
import sys
import tempfile

MARKER = "##TBS##"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WF = os.path.join(ROOT, ".github", "workflows")

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"

# workflow file -> the marker it tests for
CASES = {
    "agw-dispatch.yml": "@agy",
    "agy-issue-bot.yml": "@agy",
    "agy-plan-bot.yml": "@agy-plan",
    "agy-plan-dispatch.yml": "@agy-plan-approved",
}


def extract_step(path):
    """Pull the check-marker `run:` body out of the workflow and return it as
    a runnable script, so this probe exercises the REAL test."""
    import yaml
    with io.open(path, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
    # Keyed on what the step DOES (emits match=), not on the fix being
    # present. The first draft looked for "strip_footer", so against the
    # pre-fix workflows it reported "step not found" instead of reproducing
    # the real failure -- a negative control that proves the patch is absent
    # is weaker than one that shows the old code getting the wrong answer.
    for job in doc.get("jobs", {}).values():
        for step in job.get("steps", []) or []:
            body = step.get("run") or ""
            if "match=true" in body and "@agy" in body:
                return body
    return None


def run_step(script, title, body):
    """Execute the extracted step and return its match= output."""
    out = tempfile.NamedTemporaryFile("w+", delete=False)
    out.close()
    env = dict(os.environ)
    env.update({"TITLE": title, "BODY": body, "GITHUB_OUTPUT": out.name})
    res = subprocess.run(["bash", "-s"], input=script, text=True,
                         capture_output=True, env=env)
    with io.open(out.name, encoding="utf-8") as fh:
        printed = fh.read()
    os.unlink(out.name)
    if res.returncode != 0:
        return "ERROR: %s" % res.stderr.strip()[:200]
    m = re.search(r"match=(\w+)", printed)
    return m.group(1) if m else "NO-OUTPUT"


def main():
    failures = []
    for name, marker in sorted(CASES.items()):
        path = os.path.join(WF, name)
        script = extract_step(path)
        if script is None:
            failures.append("%s: no check-marker step with a strip_footer "
                            "found -- removed, or renamed (fix this probe)"
                            % name)
            continue

        body = "task text here\n\nccp %s" % marker
        cases = [
            # (label, title, body, expected match)
            ("plain marker", "t", body, "true"),
            ("marker + appended footer", "t", body + FOOTER, "true"),
            ("marker + footer + trailing blank lines", "t",
             body + FOOTER + "\n\n\n", "true"),
            ("marker + Co-Authored-By trailer", "t",
             body + "\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
             "true"),
            # The negative half. If any of these fire, the trigger has become
            # "mentions the marker anywhere" and quoting it dispatches a fleet.
            ("marker buried mid-comment", "t",
             "we should end with ccp %s\n\nbut here is more text after it"
             % marker, "false"),
            ("no marker at all", "t", "just a normal comment", "false"),
            ("marker inside a code fence, text after", "t",
             "example:\n```\nccp %s\n```\nthat is how you trigger it" % marker,
             "false"),
        ]
        for label, title, text, want in cases:
            got = run_step(script, title, text)
            if got != want:
                failures.append("%s / %s: match=%s, expected %s"
                                % (name, label, got, want))

    status = "fail" if failures else "pass"
    if failures:
        print("FAIL: %d finding(s):" % len(failures))
        for f in failures:
            print("  - %s" % f)
    else:
        print("PASS: all four triggers fire through an appended attribution "
              "footer, and still refuse a marker that is merely mentioned "
              "mid-comment or inside a code fence.")
    print(MARKER + json.dumps(
        {"v": 1, "probe": "marker_footer_tolerance", "status": status,
         "data": {"failures": failures, "workflows": sorted(CASES)}},
        sort_keys=True))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
